//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bangom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.SiparisUrun = new HashSet<SiparisUrun>();
        }
    
        public int SiparisID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<decimal> SiparisTutar { get; set; }
        public string Durum { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public Nullable<int> BankaID { get; set; }
        public Nullable<int> KargoID { get; set; }
    
        public virtual Banka Banka { get; set; }
        public virtual Kargo Kargo { get; set; }
        public virtual Uye Uye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisUrun> SiparisUrun { get; set; }
    }
}
