//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bangom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunKampanya
    {
        public int UrunKampanyaID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public string UrunKampanyaAdi { get; set; }
        public Nullable<decimal> YeniFiyat { get; set; }
        public Nullable<System.DateTime> UrunKampanyaBaslangic { get; set; }
        public Nullable<System.DateTime> UrunKampanyaBitis { get; set; }
    
        public virtual Urun Urun { get; set; }
    }
}
